### ISSUE TITLE
Si no existe el nodo da error

### ISSUE THREAD

**Issue by Jorge-Mauricio-Rodriguez** [soyleninjs/light-masonry#1]
https://github.com/soyleninjs/light-masonry/blob/b0a1d0896b2365a5b112b6bcde6cf3e0559261d5/js/light-masonry.js#L16

Se podria poner una comprobación para que compruebe la existencia del nodo, en caso de que no exista, no hacer mada

**Comment by soyleninjs** [comment]
Hola, a partir de la version [v1.0.4](https://github.com/soyleninjs/light-masonry/releases/tag/v1.0.4) se corrigió este problema, ahora te lanzara un mensaje en consola para saber mas de lo que esta pasando.
