### ISSUE TITLE
Aplicar una function debounce

### ISSUE THREAD

**Issue by Jorge-Mauricio-Rodriguez** [soyleninjs/light-masonry#2]
https://github.com/soyleninjs/light-masonry/blob/b0a1d0896b2365a5b112b6bcde6cf3e0559261d5/js/light-masonry.js#L204

Recomendaria aplicar una function debounce en el resize.. para que asi no se aplique exactamente en cada pixel que se recorrio en el resize.... si no que solo al finaaal fianlisimo de que terminaste de hacer resize, esto aligera mucho el computo a realizar

**Comment by soyleninjs** [comment]
Hola, a partir de la version [v1.0.4](https://github.com/soyleninjs/light-masonry/releases/tag/v1.0.4) se agrego una nueva opción la cual puedes activar el debounce y colocar con cuanto delay trabajara 🎉
